### ISSUE TITLE
The models/msi/product.proto:14:9: "google.protobuf.Timestamp" is not defined 

### ISSUE THREAD

**Issue by Debayan-Sarkar** [s77rt/rdpcloud#1]
go install mvdan.cc/garble@v0.7.2
go install github.com/s77rt/xor/cmd/xor@latest
cd cert && bash gen.sh
.+..+...+.......+.........+..+.........+...+...+....+.....+.+...+..+.........+.+..+.+..+.........+...+.+.........+.....+.+......+++++++++++++++++++++++++++++++++++++++++++++*.+......+....+...+.....+++++++++++++++++++++++++++++++++++++++++++++*.......................+......+..+.......+..+.............+......+.....+....+........+....+...............+......+..+.............+..+.............+...+..+..........+..+.+...........+..................+.+..+...+..........+.....+.......+.....+.......+........+...+.+.........+............+.....+.......+.....+......................+...+..+.+.................+.+.....................+.....+......+.........+.............+........+..........+.........+.....+....+.....+......+..........+.....+.+..+..........+......+.........+..+.+..+.+..+.........+........................+.+...+......+.....+.......+.....+............+...+....+...........+............+...+....+.........+.....+.+......+...+..+............+.+.....+......+...+.......+......+............+...+...............................................+.......+...+...+........+.+.....+.+.....+.......+...+............+........+.......+......+.............................+..........+...........+.+........+.+.........+...+.........+.....+.+....................+....+........+...+...............+...+.......+...+...........+..........+........+...........................+.+.....+......................+.....+......+......+...+......+.........+.+..+...+.......+.........+.....+.+..................+...........................+..+.+..+...+.........+.............+..+...+....+...+..+...+................+........................+......+++++
...+.+..+...+..........+............+...+...........+.+..+...+.........+++++++++++++++++++++++++++++++++++++++++++++*....+..........+.........+...+..+...+.+.....+.......+..+.......+...+..+.+....................+....+......+..+...+...+..........+...............+..+....+........+......+.+........+.......+........+.............+........+.+........+...+++++++++++++++++++++++++++++++++++++++++++++*..+.............................+.+.....+.........+..........+.....+................+......+.....+......+...+......+.........................+..................+...+.....+....+...+...........+......+.+..+.+.....+.+.....+.+...........................+..+...+...+.........+...+......+....+.....+.+....................+.+......+..+............+......+.........................+..+.+..............+.....................+.+...............+......+.....+....+...+..+......+.......+...........+.......+.....+.......+........+...+++++
-----
rm -rf proto/go && mkdir -p proto/go && touch proto/go/.keep
cd proto/go && go mod init github.com/s77rt/rdpcloud/proto/go
go: creating new go.mod: module github.com/s77rt/rdpcloud/proto/go
protoc --proto_path=proto/proto --go_out=proto/go --go_opt=paths=source_relative --go-grpc_out=proto/go --go-grpc_opt=paths=source_relative proto/proto/*/*/*.proto
**google/protobuf/timestamp.proto: File not found.**
models/msi/product.proto:7:1: Import "google/protobuf/timestamp.proto" was not found or had errors.
models/msi/product.proto:14:9: "google.protobuf.Timestamp" is not defined.
make: *** [Makefile:55: gen-go] Error 1

**Comment by s77rt** [comment]
Make sure you install the latest version of protoc. Please check https://grpc.io/docs/protoc-installation/

**Comment by s77rt** [comment]
I'm closing this since it's not a bug in rdpcloud
